server:
  port: 8069
  connection-timeout: 5000
  tomcat:
    accesslog:
      enabled: false #关闭日志
      buffered: true
      directory: ${LOG_HOME:-.}/logs/access_log  #日志文件生成路径
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhome?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false