server:
  port: 8066
  connection-timeout: 5000
  tomcat:
    accesslog:
      enabled: false #关闭日志
      buffered: true
      directory: ${LOG_HOME:-.}/logs/access_log  #日志文件生成路径
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  datasource:
    #多数据源配置url要使用jdbcUrl;mysql5与mysql6的driver-class-name不同，后者要加cj
    master:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/jsoms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://127.0.0.1:23306/jsctiptv4?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

logging:
  level:
    com.zaxxer.hikari: debug